version: "3.7"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      TZ: "Asia/Yekaterinburg"
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_HOST: 'postgres'
    ports:
      - 5432:5432

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: 'postgres://postgres:password@postgres:5432/postgres'
    depends_on:
      - postgres
